- repo: git://github.com/pre-commit/pre-commit-hooks
  sha: HEAD
  hooks:
    - id: flake8
    - id: check-ast
    - id: detect-private-key
    - id: detect-aws-credentials
    - id: check-merge-conflict
    - id: end-of-file-fixer
    - id: requirements-txt-fixer
    - id: trailing-whitespace
