sudo: false
language: rust
cache: cargo
rust:
  - stable
  - beta
  - nightly

# matrix:
#   allow_failures:
#     - rust: nightly

addons:
  apt:
    packages:
      - build-essential
      - libudev-dev

before_install:
  - pkg-config --list-all
  - pkg-config --libs libudev
  - pkg-config --modversion libudev
  - cargo install rustfmt || true

script:
- |
  cargo fmt -- --write-mode=diff &&
  cargo build &&
  cargo test
- |
  if [ "$TRAVIS_RUST_VERSION" == "nightly" ] ; then
    export LSAN_OPTIONS=verbosity=1:log_threads=1
    export ASAN_OPTIONS="detect_odr_violation=1:leak_check_at_exit=0:detect_leaks=0"
    export RUST_BACKTRACE=full
    export RUSTFLAGS="-Z sanitizer=address"
    rustup run nightly cargo test
  fi
